package com.vole.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-03-08T11:25:17.600+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://webservice.vole.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://webservice.vole.com/", className = "com.vole.webservice.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://webservice.vole.com/", className = "com.vole.webservice.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRole", targetNamespace = "http://webservice.vole.com/", className = "com.vole.webservice.GetRole")
    @ResponseWrapper(localName = "getRoleResponse", targetNamespace = "http://webservice.vole.com/", className = "com.vole.webservice.GetRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.vole.webservice.MyRoleArray getRole();

    @WebMethod
    @RequestWrapper(localName = "getRoleByUser", targetNamespace = "http://webservice.vole.com/", className = "com.vole.webservice.GetRoleByUser")
    @ResponseWrapper(localName = "getRoleByUserResponse", targetNamespace = "http://webservice.vole.com/", className = "com.vole.webservice.GetRoleByUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.vole.webservice.Role> getRoleByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.vole.webservice.User arg0
    );
}
